# .github/workflows/ci.yml  (at REPO ROOT)
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: server   # 👈 run all commands from /server
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Make mvnw executable (Linux)
        run: chmod +x mvnw

      - name: Build (skip tests)
        run: ./mvnw -q -DskipTests package

      - name: Run tests
        run: ./mvnw -q test
